.catalog:
  name: "Elasticsearch"
  version: "5.2.2-rancher1"
  description: "Elasticsearch. You know, for search"
  questions:
    - variable: es_version
      description: "Version of Elasticsearch to install."
      label: "Elasticsearch Version"
      type: "string"
      required: true
      default: "5.2.2"
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "es"
    - variable: storage_size
      description: "Amount of storage in GB to use on data nodes for persistent storage."
      label: "Storage Size"
      type: "int"
      required: true
      default: "30"
    - variable: "kopf_port"
      label: "Public Port"
      description: "Unique public port for kopf"
      type: "int"
      default: 80
      required: true
    - variable: "java_memory"
      label: "Java Heap Size (GB)"
      description: "Allows you to set the default heap size for ES Java"
      type: "int"
      default: 2
      required: true
    - variable: "master_count"
      label: "ES Master Count"
      description: "Set the count of ElasticSearch masters to spin up"
      type: "int"
      default: 1
      required: true
    - variable: "minimum_master_nodes"
      label: "ES Min Master Nodes"
      description: "Set the value of this to usually masters - 1"
      type: "int"
      default: 1
      required: true
    - variable: "datanode_count"
      label: "ES Datanode Count"
      description: "Set the count of ElasticSearch datanodes to spin up"
      type: "int"
      default: 1
      required: true
    - variable: "client_count"
      label: "ES Client Count"
      description: "Set the count of ElasticSearch clients to spin up"
      type: "int"
      default: 1
      required: true
version: '2'
services:
  elasticsearch-masters:
    scale: ${master_count}
    metadata:
      elasticsearch:
        yml:
          cluster.name: "${cluster_name}"
          node.name: "$${HOSTNAME}"
          node.data: "false"
          node.master: "true"
          node.ingest: "false"
          network.host: "_site_"
          discovery.zen.minimum_master_nodes: "${minimum_master_nodes}"
  elasticsearch-base-master:
    health_check:
      port: 9200
      request_line: GET "/_cat/health" "HTTP/1.0"
      interval: 2000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000

  elasticsearch-datanodes:
    scale: ${datanode_count}
    metadata:
      elasticsearch:
        yml:
          cluster.name: "${cluster_name}"
          node.name: "$${HOSTNAME}"
          node.data: "true"
          node.master: "false"
          node.ingest: "false"
          http.enabled: "false"
          network.host: "_site_"
  elasticsearch-base-datanode:
    health_check:
      port: 9200
      request_line: GET "/_cat/health" "HTTP/1.0"
      interval: 2000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000

  elasticsearch-clients:
    scale: ${client_count}
    metadata:
      elasticsearch:
        yml:
         cluster.name: "${cluster_name}"
         node.name: "$${HOSTNAME}"
         node.data: "false"
         node.master: "false"
         node.ingest: "true"
         network.host: "_site_"
  elasticsearch-base-clients:
    health_check:
      port: 9200
      request_line: GET "/_cat/health" "HTTP/1.0"
      interval: 2000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
